### PR TITLE
fix: auxiliary data hash mismatch during block validation.

### LINKED ISSUE #211: Failure while syncing
### What revision are you using?

4b8bd48c41018fbf3d36375ce407e6b54d00c0f3

### What operating system are you using?

Linux

### What architecture are you using?

x86_64/amd64

### What problem are you having? What should be the expected behaviour?

`amaru` crashes while syncing epoch `188`.

Also we should ensure that it makes sense to crash in this scenario.

```rust
2025-05-12T12:00:44.522621Z ERROR amaru::consensus::chain_forward: block_validation_failed slot=Slot(80153462) hash=f51bd6ea5ddcd06f710433e586104f681c484483856eca8dbbf064e553b0cc39

   amaru::fatal::error
   Whoops! The Amaru process panicked, rather than handling the error it encountered gracefully.
   
   This is almost certainly a bug, and we'd appreciate a report so we can improve Amaru.
   
   Please report this error at https://github.com/pragma-org/amaru/issues/new.
   
   In your bug report please provide the information below and if possible the code
   that produced it.
   
   Operating System: macos
   Architecture:     aarch64
   Version:          v0.1.0+4b8bd48
   

thread '<unnamed>' panicked at crates/amaru/src/stages/consensus/forward_chain.rs:270:21:
assertion `left == right` failed
  left: 3047776
 right: 3047775
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-05-12T12:00:44.523131Z ERROR gasket::framework: x=error sending work unit through output port
2025-05-12T12:00:44.523141Z ERROR gasket::runtime: stage should stop retry=Retry(None)
2025-05-12T12:00:44.523178Z ERROR gasket::framework: x=error sending work unit through output port
2025-05-12T12:00:44.523189Z ERROR gasket::runtime: stage should stop retry=Retry(None)
2025-05-12T12:00:44.523214Z ERROR gasket::framework: x=error sending work unit through output port
2025-05-12T12:00:44.523222Z ERROR gasket::runtime: stage should stop retry=Retry(None)
2025-05-12T12:00:45.073658Z ERROR gasket::framework: x=error sending work unit through output port
2025-05-12T12:00:45.073681Z ERROR gasket::runtime: stage should stop retry=Retry(None)
2025-05-12T12:00:45.073789Z ERROR gasket::runtime: stage should stop retry=Retry(None)
2025-05-12T12:00:45.113424Z ERROR gasket::framework: x=error sending work unit through output port
2025-05-12T12:00:45.113443Z ERROR gasket::runtime: stage should stop retry=Retry(None)
2025-05-12T12:00:45.113490Z ERROR gasket::framework: x=error sending work unit through output port
2025-05-12T12:00:45.113513Z ERROR gasket::runtime: stage should stop retry=Retry(None)
```

### If possible, provide reproductions steps.

_No response_

### If any, provide logs / error outputs from the system when the problem occurs.

_No response_

### Please confirm that you've already searched issues, CHANGELOG and available documentation.

- [x] I searched, but no luck.

### PR DESCRIPTION
**Pull request by KtorZ**
This was due to how the aux data was re-serialized in order to compute its hash; thus changing the hash in some cases due to the lack of canonical serialisation.

As a rule of thumb, we should BAN the use of 'compute_hash' from the ledger crate almost entirely. There's (almost certainly?) no place where we would want to reserialize anything to compute hash. The hash should always come from raw bytes.

Note that synchronization (on PreProd at least) can now go through, but eventually fails with another (funny?) error which I intend to fix in an upcoming commit:

  ```
  Block invalid: Transaction ebd7cda7805bc5b89c0fb3c8ad44f6549ab72c1040eb47019146e3f5f98298e1 at index 0 is invalid: invalid transaction scripts: missing required datums: missing [55c411e7de48dc7c81df24f6450180a702578fe9f381c63dade02d20c391581c] provided [55c411e7de48dc7c81df24f6450180a702578fe9f381c63dade02d20c391581c]
 ```

Fixes #211

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved handling of auxiliary data associated with transactions, now using a hash representation for enhanced consistency and reliability.
- **Tests**
	- Updated and expanded test cases to reflect changes in auxiliary data handling, ensuring accurate validation of transaction metadata.

### CODE REVIEW

**Comment by KtorZ** [comment]
The PR is self contained though, I can make another one for the new problem.

File: crates/amaru-ledger/src/rules/transaction.rs [hunk 1]
```diff
@@ -92,7 +92,7 @@ pub fn execute(
     is_valid: bool,
     transaction_body: KeepRaw<'_, MintedTransactionBody<'_>>,
     transaction_witness_set: &MintedWitnessSet<'_>,
-    transaction_auxiliary_data: Option<&AuxiliaryData>,
+    transaction_auxiliary_data: Option<Hash<32>>,
```
Comment (yHSJ) [inline crates/amaru-ledger/src/rules/transaction.rs]: NITPICK: this is a bit confusing, probably should be named `transaction_auxiliary_data_hash` or something.

**Review by yHSJ — APPROVED** [review]
Thanks for fixing this, I left one nitpick comment regarding naming.

File: crates/amaru-ledger/src/rules/transaction.rs (hunk 1 above)
Comment (KtorZ) [reply crates/amaru-ledger/src/rules/transaction.rs]: I agree; I was looking in despair for such a type alias in Pallas, without success.

On second thought, could have added it to amaru-kernel though.

Comment (KtorZ) [reply crates/amaru-ledger/src/rules/transaction.rs]: Ho, you meant the arg name.

**Comment by jeluard** [comment]
>we should BAN the use of 'compute_hash'

It could be denied via clippy's [disallowed_methods](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods)

File: crates/amaru-ledger/src/rules/transaction.rs (hunk 1 above)
Comment (yHSJ) [reply crates/amaru-ledger/src/rules/transaction.rs]: I specifically meant the argument name, but also yes there should be an alias.
